Document: gimmage
Title: Debian gimmage Manual
Author: <insert document author here>
Abstract: This manual describes what gimmage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gimmage/gimmage.sgml.gz

Format: postscript
Files: /usr/share/doc/gimmage/gimmage.ps.gz

Format: text
Files: /usr/share/doc/gimmage/gimmage.text.gz

Format: HTML
Index: /usr/share/doc/gimmage/html/index.html
Files: /usr/share/doc/gimmage/html/*.html

  
